# 1 ETAPA CRIAR O WORD COM O ESPAÇO PARA ACRESCENTAR AS IFNORMAÇÕES
    # DADOS A COLETAR DO CLIENTE
        # NOME CLIENTE
        #CPF
        #TELEFONE   
        #ENDEREÇO   
    # DADOS A COLETAR DO EVENTO
        # NOME EVENTO
        # LOCAL EVENTO
        # DATA EVENTO
        # DIA DA SEMANA
        # HORARIO INICIO
        # HORARIO FINAL
    # ACRESCENTAR A DATA COMPLETA DA CRIAÇÃO DO CONTRATO



